apply plugin: 'com.android.application'

// Create a variable called keystorePropertiesFile, and initialize it to your
// keystore.properties file, in the rootProject folder.
def keystorePropertiesFile = rootProject.file("keystore.properties")

// Initialize a new Properties() object called keystoreProperties.
def keystoreProperties = new Properties()

// Load your keystore.properties file into the keystoreProperties object.
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))


android {
    compileSdkVersion 30
    buildToolsVersion "30.0.1"

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    defaultConfig {
        applicationId "com.coccoc.news"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField('String', 'NEWS_HOST', "\"https://coccoc.com/composer/feed/v1/\"")
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField('String', 'NEWS_HOST', "\"https://coccoc.com/composer/feed/v1/\"")
        }
    }

    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "androidx.core:core-ktx:$rootProject.core_ktx"
    implementation "androidx.appcompat:appcompat:$rootProject.appcompat"
    implementation "androidx.activity:activity:$rootProject.activity"
    implementation "androidx.fragment:fragment:$rootProject.fragment"
    implementation "androidx.recyclerview:recyclerview:$rootProject.recyclerview"
    implementation "androidx.cardview:cardview:$rootProject.cardview"
    implementation "com.google.android.material:material:$rootProject.material"
    implementation "androidx.preference:preference:$rootProject.preference"
    implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.lifecycle"
    implementation "com.github.bumptech.glide:glide:$rootProject.glide"
    implementation "androidx.room:room-runtime:$rootProject.room"
    implementation "androidx.room:room-ktx:$rootProject.room"
    annotationProcessor "android.arch.persistence.room:compiler:$rootProject.room"
    testImplementation "androidx.room:room-testing:$rootProject.room"
    implementation "com.squareup.retrofit2:retrofit:$rootProject.retrofit"
    implementation "com.squareup.retrofit2:converter-gson:$rootProject.retrofit"
    implementation "com.squareup.retrofit2:converter-scalars:$rootProject.retrofit"
    implementation 'com.squareup.okhttp3:logging-interceptor:3.8.0'
    implementation "androidx.paging:paging-runtime:$rootProject.paging"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

}